name: Update Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点运行
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main
  repository_dispatch:  # 通过 API 触发
  watch:  # 监听源仓库更新

# 添加权限配置
permissions:
  contents: write  # 允许创建和推送分支
  pull-requests: write  # 允许创建和更新 PR

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          ref: main  # 先检出 main 分支

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate rules
        run: |
          python generate_rules.py

      - name: Check generated files
        run: |
          # 检查规则文件是否生成
          if [ ! -d "geosite" ] || [ ! -d "geoip" ]; then
            echo "错误：规则文件未生成"
            exit 1
          fi
          # 检查更新相关文件是否生成
          if [ ! -f "rule_hashes.json" ] || [ ! -f "update_report.txt" ]; then
            echo "错误：更新相关文件未生成"
            exit 1
          fi

      - name: Create release branch
        run: |
          # 如果 release 分支已存在，先删除
          git branch -D release || true
          # 创建新的 release 分支
          git checkout --orphan release
          # 删除所有文件
          git rm -rf --cached .
          # 添加规则文件和更新相关文件
          git add -f geosite/ geoip/ rule_hashes.json update_report.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "chore: update rules and rule hashes"

      - name: Push to release branch
        run: |
          git push origin release --force

      - name: Prepare release files
        run: |
          # 创建发布目录
          mkdir -p release
          # 复制并重命名规则文件到发布目录
          for file in geosite/*.list; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              cp "$file" "release/geosite-${filename}.list"
            fi
          done
          for file in geoip/*.list; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              cp "$file" "release/geoip-${filename}.list"
            fi
          done
          # 创建发布说明
          echo "# ACL4SSR 规则文件" > release/README.md
          echo "" >> release/README.md
          echo "## 规则文件列表" >> release/README.md
          echo "" >> release/README.md
          echo "### Geosite 规则" >> release/README.md
          ls -1 release/geosite-*.list | sed 's/release\/geosite-//' | sed 's/\.list$//' | while read file; do
            echo "- $file" >> release/README.md
          done
          echo "" >> release/README.md
          echo "### GeoIP 规则" >> release/README.md
          ls -1 release/geoip-*.list | sed 's/release\/geoip-//' | sed 's/\.list$//' | while read file; do
            echo "- $file" >> release/README.md
          done

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## 更新内容
            - 更新规则文件
            - 更新规则哈希值
            - 更新报告文件
            
            ## 文件变更
            - geosite/ 目录
            - geoip/ 目录
            - rule_hashes.json
            - update_report.txt
            
            ## 自动更新
            此版本由 GitHub Actions 自动生成
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/*.list
          asset_name: rules-${{ github.run_number }}.list
          asset_content_type: text/plain 